// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgeattviopkcsenqjtqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZWF0dHZpb3BrY3NlbnFqdHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTE3NTUsImV4cCI6MjA2MjEyNzc1NX0.GR8XDSrKwwLshU6DPxM1st0NfAV9HnImliAANwzR2ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);